Fix LightNode look at
SceneView/sceneview-android pull request #124
Opened 2022-07-20 14:59 UTC by SeyedAlirezaFatemi

2022-07-22 09:59 UTC, grassydragon requested changes
Thank you! Just some small comments about comments :slightly_smiling_face:

2022-07-22 09:59 UTC, grassydragon commented on sceneview/src/main/java/io/github/sceneview/node/Node.kt
> +        // targetPosition is passed as eye so that the forward direction will be towards the target
I think it will be better to use a common style of comments (before the `look...` call or inside the arguments).

2022-07-22 09:59 UTC, grassydragon commented on sceneview/src/main/java/io/github/sceneview/node/Node.kt
> +            -lookDirection, // lookDirection is negated so that the forward direction will be aligned with the lookDirection
If we put a comment inside the arguments, we can also put it on the preceding line.

2022-07-24 07:36 UTC, grassydragon approved these changes

2022-07-24 07:36 UTC, grassydragon commented on sceneview/src/main/java/io/github/sceneview/node/LightNode.kt
> +    ) = // SPOTLIGHT and FOCUSED_SPOTLIGHT radiate light along their -forward axis.
Should we use a block body here?

2022-07-24 11:20 UTC, ThomasGorisse commented
Please don't merge yet

2022-07-25 07:30 UTC, SeyedAlirezaFatemi commented
There is one problem:
If the parent is doing a smooth transform, then the `worldToParent` that we use in the child is based on the parent's transform not `smoothTransform` and that causes problems. For example if we do this:
```kotlin
parentNode.lookAt(sceneView.camera.worldPosition, smooth = true)
childNode.lookAt(sceneView.camera.worldPosition, smooth = true)
```
the child will do a wrong rotation and it's like it does double the rotation that was needed to look at the camera and will end up not looking at the camera.
Any ideas how we can fix this?

2022-07-25 07:33 UTC, SeyedAlirezaFatemi commented on sceneview/src/main/java/io/github/sceneview/node/LightNode.kt
> +    ) = // SPOTLIGHT and FOCUSED_SPOTLIGHT radiate light along their -forward axis.
Done!

2022-11-01 06:01 UTC, closed without merging