Fix for rendering semi-transparent models and plane renderer
SceneView/sceneview-android pull request #259
Opened 2023-04-27 11:34 UTC by kiler222

Configure the `renderable` to use only 1 channel.

2023-04-27 13:40 UTC, grassydragon requested changes
Thanks for spotting this error!
However, the parameter rather defines the number of primitives: https://github.com/google/filament/blob/899c15f02301ae757cdb8054322ca7a4af6256a3/android/filament-android/src/main/java/com/google/android/filament/RenderableManager.java#L124
Could you update the pull request description and commit message to reflect that?

2023-04-27 14:19 UTC, grassydragon commented
@ThomasGorisse
Do you remember why we had to set the channel number to 3?
https://github.com/SceneView/sceneview-android/commit/cd6d0cea56fabd85c74aada542b1f14abcc175cc#diff-06d11f1033730f3791ef91200f04eaf3b4b05f00d0db2a09e0cfc7d83ae0e5caR176

2023-04-27 21:34 UTC, ThomasGorisse commented
@grassydragon Please remove it.
So the PR is fixing something at the end?

2023-04-28 07:08 UTC, kiler222 commented
>  So the PR is fixing something at the end?

@ThomasGorisse 

The ArSceneView 0.9.7
![version-0 9 7](https://user-images.githubusercontent.com/43797319/235078596-5b908510-9a0a-42d5-81cf-97a6d77f9708.png)

The fix applied.
![fix](https://user-images.githubusercontent.com/43797319/235078763-30ef3c49-5a59-4581-9284-84a83907d0f1.png)

2023-04-28 08:49 UTC, grassydragon commented
@kiler222
Great! But is it possible to remove the `channel` call completely to use the default second channel?

2023-04-28 10:16 UTC, kiler222 commented
> @kiler222 Great! But is it possible to remove the `channel` call completely to use the default second channel?

In 0.9.7 the Filament 1.31.4 is used, where the default channel is 0. Only from [Filament 1.31.6](https://github.com/google/filament/releases/tag/v1.31.6) the default channel is 2. 
Do you plan to upgrade filament in the next release? 

Sure I can remove the `channel(0)` and leave it to to the default value.

2023-04-28 10:29 UTC, grassydragon commented
> Do you plan to upgrade filament in the next release?

Probably, so it's better to use the default value.

2023-04-28 10:30 UTC, grassydragon approved these changes

2023-04-28 10:39 UTC, merged

2023-12-29 07:06 UTC, dhaval-android commented
Hello @kiler222 
Can you guide how achieve above second ui, I want to draw a model with a plan tracker and want move with the plan finder, Can you guide plz