call arcore.destroy off of main thread
SceneView/sceneview-android pull request #408
Opened 2024-02-05 21:42 UTC by sameerjj

## Problem
- getting Crashlytics reports of ANR and user reports of app hanging when closing AR activity
## Solution
- from ArCore Session documentation:
> Releases resources (a significant amount of native heap memory) used by an ARCore session.
Failure to close sessions explicitly may cause your app to run out of native memory and crash. If your app contains a single AR-enabled activity, it is recommended that you call close() from the activity's onDestroy method.
**This method will take several seconds to complete. To prevent blocking the main thread, call pause() on the main thread, and then call close() on a background thread.**

- use coroutine scope to call destroy off of MainThread

2024-02-05 21:46 UTC, sameerjj commented
Fixes #407

2024-02-05 22:32 UTC, ThomasGorisse requested changes

2024-02-05 22:32 UTC, ThomasGorisse commented on arsceneview/src/main/java/io/github/sceneview/ar/ARSceneView.kt
> +    fun destroyAr() {
```suggestion
    open fun destroyARCore() {
```

2024-02-05 22:32 UTC, ThomasGorisse commented on arsceneview/src/main/java/io/github/sceneview/ar/ARSceneView.kt
> +            destroyAr()
```suggestion
            destroyARCore()
```

2024-02-06 10:19 UTC, ThomasGorisse approved these changes
Thanks !

2024-02-06 10:20 UTC, merged

2024-03-06 10:37 UTC, Antiglobalist commented
@ThomasGorisse @sameerjj Hi !
I have updated SDK version to 2.0.4.
And i faced with NDK exception:
![image](https://github.com/SceneView/sceneview-android/assets/6048753/82028e2c-491c-449f-b797-cf28eb14eccd)

In my App flow I finish AR activity and start other one(Not AR)
I don't have any extra calls on Destroy state
![image](https://github.com/SceneView/sceneview-android/assets/6048753/a8444546-7976-46de-a408-918a4b06cdc5)

I suppose it's happening cuz destroyARCore function is not thread safe inside now. And arCore.destroy() is calling twice
![image](https://github.com/SceneView/sceneview-android/assets/6048753/99bddf7a-0ae4-42e3-ad3a-43a5eecd8856)