Enable own implementation of camera manipulator
SceneView/sceneview-android pull request #571
Opened 2024-10-14 21:45 UTC by kubax2000

# Problem
Curently is not possible to modify camera manipulator therefore, neither the orbit, pan and zoom behavior. (Some settings are available via Modifier.Builder(), but for more advanced usage are not sufficient enough.)

# Solution
I added CameraManipulator interface to make this possible. Default implemantation (DefaultCameraManipulator) stil uses filament`s manipulator.

2024-10-15 05:16 UTC, ThomasGorisse approved these changes

2024-10-15 05:23 UTC, ThomasGorisse requested changes
Can you please fix the build?

2024-10-15 11:22 UTC, ThomasGorisse approved these changes

2024-10-16 12:08 UTC, kubax2000 commented
Fixed and tested. (https://github.com/kubax2000/sceneview-android/actions/runs/11365138094/job/31612658647)

2024-10-19 16:51 UTC, merged